# -*- coding: utf-8 -*-
{
    'name': "Smart Electric Charger",
    'summary': """Smart Electric Charger""",
    'sequence': 0,
    'description': """Smart Electric Charger""",
    'author': "ULTS",
    'website': "https://ults.in",
    'category': 'Productivity',
    'version': '0.1',
    'depends': ['base','website','report_xlsx','muk_web_theme'],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'data/customer_sequence.xml',
        'data/cm_vehicle.xml',
        'data/station.xml',
        'data/manager.xml',
        'data/mail_template.xml',
        'report/report_card.xml',
        'report/report.xml',
        'wizard/search_station.xml',
        'wizard/charge_now.xml',
        'wizard/payment_wizard.xml',
        'wizard/appointment_wizard.xml',
        'views/payment.xml',
        'views/company.xml',
        'views/booking_customer.xml',
        'views/district.xml',
        'views/time.xml',
        'views/type.xml',
        'views/place.xml',
        'views/charge.xml',
        'views/add_vehicle.xml',
        'views/cm_variant.xml',
        'views/customer_view.xml',
        'views/cus_add_vehicle.xml',
        'views/manager_view.xml',
        'views/booking.xml',
        'views/cm_electric_vehicle.xml',
        'views/com_connector.xml',
        'views/man_chargestation.xml',
        'views/template.xml',
        'views/menu.xml',
    ],
    'demo': [
        # 'demo/demo.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
